server:
  port: 6060

# JSP 경로 설정
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MYSQL;
    # driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2
  sql:
    init:
      schema-locations: classpath:h2/schema.sql
      data-locations: classpath:h2/data.sql
      encoding: UTF-8
      mode: always

mybatis:
  mapper-locations: classpath:mapper/*_mapper.xml
  configuration:
    map-underscore-to-camel-case: true

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    operations-sorter: method

# 로그 관련 설정
logging:
  file:
    # / 를 붙이면 C드라이브 하위 폴더 생성됨
    # / 를 안 붙이면 프로젝트 내부에 폴더 생성됨
    name: log/todo.log
    # 로그를 남길 데이터의 위험도
    # TRACE < DEBUG < INFO < WARN < ERROR < FATAL
  level:
    root: warn
  charset:
    file: UTF-8